### ISSUE TITLE
[FEATURE]: Add MDN logo 

### ISSUE THREAD

**Issue by Shariar-Hasan** [Shariar-Hasan/ProGos#10]
get assigned, get merged.

but must read the [contribution guideline](https://github.com/Shariar-Hasan/ProGos/blob/main/Contributing.md#what-can-you-do)

**Comment by dipayansarkar47** [comment]
I can do this, can you assign it to me?

**Comment by Shariar-Hasan** [comment]
yeah sure, dont forget to star the repo(help us grow)
and read the contribution guideline.
you are assigned

**Comment by dipayansarkar47** [comment]
Hey @Shariar-Hasan, I made a PR on this issue, can you please review it : )
