### ISSUE TITLE
[FEATURE]: Add Html logo

### ISSUE THREAD

**Issue by Honeshwar** [Shariar-Hasan/ProGos#15]
### What do you want to change? 
I want to add a feature.

Assign me this issue with hacktoberfest label.

### Screenshot

![html](https://github.com/Shariar-Hasan/ProGos/assets/73346917/042e28dd-8034-4677-9f8e-f249fb5c8346)
![html (1)](https://github.com/Shariar-Hasan/ProGos/assets/73346917/c7bfc741-129d-41f9-9d0f-55720b4aaf85)
![html (2)](https://github.com/Shariar-Hasan/ProGos/assets/73346917/09858ce5-40d9-4e93-82fa-d28a11fa71a6)

..soon

### Conditions check:

- [x] i have read the [contribution guideline](https://github.com/Shariar-Hasan/ProGos/blob/main/Contributing.md#what-can-you-do)

- [x] i am sure, this issue is not raised before.

- [x] i will try to do Implement the feature properly.

**Comment by Shariar-Hasan** [comment]
assigned
dont worry about the data.js and readme.md
i will update those later.
you can add html logos
