### ISSUE TITLE
[FEATURE]: Add Exercism Logo

### ISSUE THREAD

**Issue by thegauravgiri** [Shariar-Hasan/ProGos#20]
### What do you want to change? 
 
I would like to add [Exercism](https://exercism.org/) Logos of all sizes.

### Conditions check:

- [x] i have read the [contribution guideline](https://github.com/Shariar-Hasan/ProGos/blob/main/Contributing.md#what-can-you-do)

- [x] i am sure, this issue is not raised before.

- [x] i will try to do Implement the feature properly.

**Comment by Shariar-Hasan** [comment]
sure
