### ISSUE TITLE
[FEATURE]: Add Hover Effect for cards

### ISSUE THREAD

**Issue by thegauravgiri** [Shariar-Hasan/ProGos#21]
### What do you want to change? 

The UI would look better if there was a hover effect on the cards. Therefore, I would like to add the hovereffect.

### Screenshot
![progos](https://github.com/Shariar-Hasan/ProGos/assets/64427471/1cb6dc27-be79-45fa-a498-9b76d236165b)

### Conditions check:

- [x] i have read the [contribution guideline](https://github.com/Shariar-Hasan/ProGos/blob/main/Contributing.md#what-can-you-do)

- [x] i am sure, this issue is not raised before.

- [x] i will try to do Implement the feature properly.

**Comment by Shariar-Hasan** [comment]
assigend
