### ISSUE TITLE
[FEATURE]: Add Javascript logo

### ISSUE THREAD

**Issue by urwah1248** [Shariar-Hasan/ProGos#23]
### What do you want to change? 

Add the Javascript Logo

### Screenshot

![image](https://github.com/Shariar-Hasan/ProGos/assets/107793187/ffb98233-ec00-4f98-9fff-54033844dba7)

### Conditions check:

- [x] i have read the [contribution guideline](https://github.com/Shariar-Hasan/ProGos/blob/main/Contributing.md#what-can-you-do)

- [x] i am sure, this issue is not raised before.

- [x] i will try to do Implement the feature properly.

**Comment by dipayansarkar47** [comment]
Hey @urwah1248 , I wanted to work on this, can you please assign this task to me : )
