### ISSUE TITLE
[FEATURE]: Add StuckOverFlow Logo

### ISSUE THREAD

**Issue by Shariar-Hasan** [Shariar-Hasan/ProGos#6]
If Anyone interested, get assigned.
but you must follow contribution guideline to make a PR.

**Comment by YashM211** [comment]
Can I get this one

**Comment by Shariar-Hasan** [comment]
sure,
star the repo,
and just take a minute to read the contribution guideline(which is imporntent for getting merged)

**Comment by dipayansarkar47** [comment]
Hey @Shariar-Hasan, It's been 4 days but nobody updated on this issue, can you assign it to me : )

**Comment by Shariar-Hasan** [comment]
> Hey @Shariar-Hasan, It's been 4 days but nobody updated on this issue, can you assign it to me : )
@dipayansarkar47  hello,

acctually updated,
he made a pull request with some mistakes,
its on review.
thats why we are taking one week waiting,
if he doesnt give any response, you will be assigned.
