### ISSUE TITLE
[FEATURE]: Add W3School logo

### ISSUE THREAD

**Issue by Shariar-Hasan** [Shariar-Hasan/ProGos#7]
get assigned, get merged.

but must read the [contribution guideline](https://github.com/Shariar-Hasan/ProGos/blob/main/Contributing.md#what-can-you-do)

**Comment by thegauravgiri** [comment]
I would like to work on this too.

**Comment by Shariar-Hasan** [comment]
yeah sure,
you know the procedure ,
assigning you
