### ISSUE TITLE
[FEATURE]: Add Sololearn Logo

### ISSUE THREAD

**Issue by Shariar-Hasan** [Shariar-Hasan/ProGos#8]
get assigned, get merged.

but must read the [contribution guideline](https://github.com/Shariar-Hasan/ProGos/blob/main/Contributing.md#what-can-you-do)

**Comment by thegauravgiri** [comment]
@Shariar-Hasan  Can I get assigned? I have collected the required sizes for the logo.

**Comment by Shariar-Hasan** [comment]
yeah, sure, why not.
