### ISSUE TITLE
[FEATURE]: Add Code.org Logo

### ISSUE THREAD

**Issue by Shariar-Hasan** [Shariar-Hasan/ProGos#9]
get assigned, get merged.

but must read the [contribution guideline](https://github.com/Shariar-Hasan/ProGos/blob/main/Contributing.md#what-can-you-do)

**Comment by thegauravgiri** [comment]
@Shariar-Hasan  Can you assign me this?

**Comment by Shariar-Hasan** [comment]
yeah, sure, please follow the contribution criteria

**Comment by thegauravgiri** [comment]
sure
